### ISSUE TITLE
AttributeError: 'Sphinx' object has no attribute 'set_translator'

### ISSUE THREAD

**Issue by oliverzgy** [odoo/documentation-user#10]
'make html' comes with this error.

The fix below works to solve the issue - 
https://github.com/odoo/odoo/commit/a139d81c46b669fa9186ceaf2a0ca43fb0601e1c

**Comment by tde-banana-odoo** [comment]
Fixed at commit 8151a78aed9d8eca1eeab44daf6b371d56014567 . The fix is the one from @xmo-odoo on odoo technical documentation. Thanks !
