### ISSUE TITLE
Live Currency Rate

### ISSUE THREAD

**Issue by Gorkygd** [odoo/documentation-user#137]
I am struggling to find the "Live Currency Rate" on the Accounting -> Configuration -> Settings. Is there probably something I might be missing?

**Comment by tivisse** [comment]
Hello @Gorkygd ,

It should be visible if the module 'currency_rate_live' is installed and it the option 'Allow multi currencies' is enabled under the account configuration. 

See : https://drive.google.com/file/d/0Bz6OpV442af-MXlsUGhuSEgySEU/view?usp=drivesdk

Tell me if you still face the issue when fitting these 2 conditions,

Yannick.
