### ISSUE TITLE
The documentation is not generated in Spanish language

### ISSUE THREAD

**Issue by hectorlicea** [odoo/documentation-user#159]
I'm trying to generate documentation in Spanish but always generated in English. I used the commands:
$ make html
or
$ make i18nhtml

Best regard, HLicea

**Comment by tivisse** [comment]
ping @mart-e

**Comment by mart-e** [comment]
You need to specify which language you are trying to build. Try with `make -e LANG=es i18nhtml`.

**Comment by samping** [comment]
i run `make -e LANG=es i18nhtml` it still  build english
