### ISSUE TITLE
Odoo9: handle kitchen & bar order printing doc

### ISSUE THREAD

**Issue by effelle** [odoo/documentation-user#174]
I think the [How to handle kitchen & bar order printing?](https://www.odoo.com/documentation/user/9.0/point_of_sale/restaurant/print.html) is missing an important part: what kind of printers you can use on Odoo restaurant module. Basically seems you can't use any local receipt printer at all (usb in my case)or one using 'localhost' or '127.0.0.1' instead of a real ip connected printer. In fact I didn't find any word about what kind of restaurant printers you can use in POS documentation [here](https://www.odoo.com/page/point-of-sale-hardware) but just

> Odoo POS can print on any web-browser compatible printer. This includes most inkjet, laser and thermal printers, connected by USB or via network. 

Again, not a word about restaurant/bar printers.
Set a printer on cups via socket like `socket://192.168.25.100:9100` to access it remotely works for receipts but not for kitchen/bar. 
Could you gently clarify the situation?
Thanks.

**Comment by tivisse** [comment]
Hello @effelle,

Thanks for the feedback. We will treat your demand and update the documentation accordingly. 

Have a nice day.

**Comment by effelle** [comment]
Thanks @tivisse, I'll have a look on it from time to time.
> Have a nice day.

Thanks, you too.

**Comment by gchiham** [comment]
Hi we have Odoo V8 with 2 printers. one usb and other via ethernet. No POSBOX.
We can print invoice on both printers, but we are planning to use ethernet printer in kitchen and when we click place order it dosent work. Is it necesarry to use the POSBOX hardware ?

Regards,

**Comment by sajjidakr** [comment]
We would appreciate if we could get an answer. Is it possible to print in kitchen by clicking order without POSBOX hardware ?

**Comment by mart-e** [comment]
> We would appreciate if we could get an answer. Is it possible to print in kitchen by clicking order without POSBOX hardware ?

No, you need one posbox per printer.
By the way, if the issue is the cost, you can always make your own with the [raspberry pi image](http://nightly.odoo.com/master/posbox/).

**Comment by aimejules** [comment]
@mart-e @sajjidakr 
I think that you can use theses modules and don't need PosBox. You can use UNLIMITED network printer (esc/pos command). You can print for PC, Smart phone or Tablet
Pos retail : https://www.odoo.com/apps/modules/12.0/pos_network_printer
Pos restaurant : https://www.odoo.com/apps/modules/12.0/pos_restaurant_network_printer

If you want to use theses modules with Odoo Saas, you add theses :
Pos retail : https://www.odoo.com/apps/modules/12.0/pos_network_printer_online
Pos restaurant : https://www.odoo.com/apps/modules/12.0/pos_restaurant_online

Please email me aimejules1@gmail.com or skype aimejules01 and I send you documentation and vidéo for demo.  You have free support also to implement it.

Thanks
