### ISSUE TITLE
[10.0] Missing link in doc

### ISSUE THREAD

**Issue by rafaelbn** [odoo/documentation-user#191]
Hello,

Reading in the documentation it looks in this line is missing a link

https://github.com/odoo/documentation-user/commit/e5c7739f7db7788afcbe585b7d8b4f92cc0e17bd#diff-de2c406f45f7dea2377559075fb780aaR38

Thanks

**Comment by tivisse** [comment]
Hello @rafaelbn 

This link to lead to a documentation page that is not written yet. This commit hides the link while waiting the page to be finished. https://github.com/odoo/documentation-user/commit/0c5e9842ce2ef3e2a6c0ae7f9ba8c687945719e2

Have a nice day.
