### ISSUE TITLE
How to get the translated documents?

### ISSUE THREAD

**Issue by djulien19** [odoo/documentation-user#195]
Where are the .po documents to get the translation part in French?
How may I extract them only to pull requests?

**Comment by tivisse** [comment]
@mart-e Can you please answer to this issue ?

**Comment by mart-e** [comment]
Hello,

The translations are done on https://www.transifex.com/odoo/odoo-9-doc
and the French translations are stored in the folder `/locale/fr/LC_MESSAGES`.
I am not sure to understand what you mean by " extract them only to pull requests?"
Let me know if you need more information.
