### ISSUE TITLE
[10.0] Missing info in documentation / terms and confitions

### ISSUE THREAD

**Issue by rafaelbn** [odoo/documentation-user#207]
Hi,

I was trying to follow the next documentation:
https://www.odoo.com/documentation/user/10.0/es/sales/quotation/setup/terms_conditions.html

But as you can check in this screenshot there is no configuration tab in Company. Test are done in runbot and my own instance

![2017-02-17_18-30-08](https://cloud.githubusercontent.com/assets/8736623/23076261/f3f5c3b2-f53f-11e6-96e6-0b9a97534959.jpg)

https://github.com/odoo/documentation-user/edit/9.0/sales/quotation/setup/terms_conditions.rst

cc @alexcbr2

**Comment by fgi-odoo** [comment]
Hello,

we updated the documentation accordingly: https://www.odoo.com/documentation/user/10.0/sales/quotation/setup/terms_conditions.html

Best regards,

Frederic Gilson
Odoo Usability Team
