### ISSUE TITLE
No info about MagTek card reader.

### ISSUE THREAD

**Issue by Ark74** [odoo/documentation-user#234]
Hi!

I'm having issues with a RPi2 using Posbox, it won't recognize the card swaping.

I did got into the terminal, and got a ton of info but no apparent error.
I do believe that there is an issue with a hardware lever. I can't see any special module loaded, at all.

Any help would be really appreciated.
Here some of the output from the RPi2.

```
cat /etc/rpi-issue 
Raspberry Pi reference 2016-09-23
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 62406bad92ed23728f46711b3539c04c37dfb62c, stage2

lsmod
Module                  Size  Used by
bnep                   10340  2 
hci_uart               17943  1 
btbcm                   5929  1 hci_uart
bluetooth             326105  22 bnep,btbcm,hci_uart
brcmfmac              186339  0 
brcmutil                5661  1 brcmfmac
cfg80211              427855  1 brcmfmac
rfkill                 16037  4 cfg80211,bluetooth
snd_bcm2835            20447  0 
snd_pcm                75762  1 snd_bcm2835
snd_timer              19288  1 snd_pcm
snd                    51908  3 snd_bcm2835,snd_timer,snd_pcm
bcm2835_gpiomem         3040  0 
bcm2835_wdt             3225  0 
usblp                  10482  0 
uio_pdrv_genirq         3164  0 
uio                     8000  1 uio_pdrv_genirq
ipv6                  347530  44

lsusb
Bus 001 Device 005: ID 0801:0011 MagTeK
```

**Comment by tivisse** [comment]
@mart-e Could you please take a look about this issue ?

Thanks.

**Comment by mart-e** [comment]
Hello,

Sorry but I am not familiar with the card reader so can't help you much. I am not even sure it integrates with the posbox iteself.
Please contact the support for issues. This is the repository for user documentation.

**Comment by ngethe** [comment]
@Ark74 

Try following this steps let me know if it goes well.

also ensure that the keyboard is as guide (us internal not qwerty)
all the best


 https://www.odoo.com/forum/help-1/question/step-by-step-guidelines-to-accept-credit-card-payments-in-odoo-pos-92896

**Comment by Ark74** [comment]
Oh hi! @ngethe 

The PosBox was not recognizing the card reader, that was it, once we plugged it to another machine, everything worked fine. Sorry can't debug the posbox anymore they were return that week.

Cheers!
