### ISSUE TITLE
How to get the file in French to make some adjustments?

### ISSUE THREAD

**Issue by djulien19** [odoo/documentation-user#245]
I would like to see the French version of the document in Github so as to make corrections.

**Comment by tivisse** [comment]
Hello @djulien19 

The translation are available on transifex (See https://www.transifex.com/odoo/odoo-10-doc/dashboard/)

All the modifications should be made from their interface.

@mart-e Shouldn't we add something in the documentation to redirect to this page ? 

Thanks.
