### ISSUE TITLE
Wrong configuration placement

### ISSUE THREAD

**Issue by mart-e** [odoo/documentation-user#259]
Reported at https://github.com/odoo/odoo/issues/22064

Was at
![approvals01](https://user-images.githubusercontent.com/564822/34666774-3fe16ddc-f466-11e7-8360-98736308eb6a.png)

is now
![](https://user-images.githubusercontent.com/6352350/34662186-0b021ace-f44f-11e7-8ff6-ed1ee284b43b.png)

**Comment by fgi-odoo** [comment]
In Odoo 11, this settings can be found in the Purchase settings, and it's company specific.

**Comment by mart-e** [comment]
Yes, I was opening an issue to say to correct the doc page 😉 
https://www.odoo.com/documentation/user/11.0/purchase/purchases/rfq/approvals.html

**Comment by fgi-odoo** [comment]
We are in the process of updating the doc. They are plenty of examples like that. No need of github issue.

**Comment by macdelacruz** [comment]
Where is that **Levels of Approval** radio buttons in Community Edition?

![selection_099](https://user-images.githubusercontent.com/13848476/34676062-70443ab4-f483-11e7-912d-65212630950f.png)

**Comment by macdelacruz** [comment]
@fgi-odoo where exactly can we find that Levels of Approval radio buttons in Odoo 11 CE?

![selection_099](https://user-images.githubusercontent.com/13848476/34906869-c86a8052-f86d-11e7-8760-46c718b886da.png)

**Comment by AntoineVDV** [comment]
Closing this issue because the feature isn't documented anymore in 12.0+ versions of the documentation.

**Comment by cdu-odoo** [comment]
Thank you @AntoineVDV :) I completely forgot this issue sorry.
