### ISSUE TITLE
Wrong github link in Mexico  User Doc 

### ISSUE THREAD

**Issue by goliveirab** [odoo/documentation-user#260]
The GitHub link here: https://www.odoo.com/documentation/user/11.0/es/accounting/localizations/mexico.html

seems to be wrong (see the image: I am in version 11.0 according to the page URL but the github link refers to v10.0):
![captura de pantalla de 2018-01-12 15-28-33](https://user-images.githubusercontent.com/5191766/34892099-56408a0e-f7ae-11e7-89e5-7e3ba94e6650.png)

When clicking it, the link refers to a non-existent page:
![image](https://user-images.githubusercontent.com/5191766/34892280-0a9ab29a-f7af-11e7-98e4-18392c3c9acb.png)

**Comment by mart-e** [comment]
Fixed at 1aa446a78366c51d23855994dbeae483a8399f8b
