### ISSUE TITLE
error when  oauth google  

### ISSUE THREAD

**Issue by momen** [odoo/documentation-user#270]
when try  login with  google   return error   Access Denied  (?oauth_error=2)

how  can solve  this  problem

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
