### ISSUE TITLE
Dead links in purchase docs 

### ISSUE THREAD

**Issue by jubodoo** [odoo/documentation-user#278]
There's dead links in the seealso of these 3 docs, as far as I know they were removed at some point, so we can just remove the see also when it links to nothing? Thanks. 

https://www.odoo.com/documentation/user/12.0/purchase/purchases/tender/manage_multiple_offers.html 
https://www.odoo.com/documentation/user/12.0/purchase/purchases/rfq/create.html

https://www.odoo.com/documentation/user/12.0/purchase/replenishment/flows/purchase_triggering.html

**Comment by mart-e** [comment]
Should be good now
