### ISSUE TITLE
locale/fr/LC_MESSAGES/iot.po contains Dutch translations

### ISSUE THREAD

**Issue by BamBalaam** [odoo/documentation-user#330]
**Example:**

#: ../../iot/connect.rst:5
msgid "Install the Internet of Things (IoT) App on your Odoo Database."
msgstr "Installeer de Internet of Things (IoT) App in uw Odoo Databank."

**Comment by rim-odoo** [comment]
@mart-e Looks that @C3POdoo exported crappy things, but I don't have the rights to check it on Transifex:
 
https://github.com/odoo/documentation-user/blame/12.0/locale/fr/LC_MESSAGES/iot.po#L34-L40

**Comment by mart-e** [comment]
How dare you criticise @C3POdoo, blame the translator, not the messenger.
Somebody translated Dutch in the French part, so got Dutch in the doc.
Removed all the Dutch part in https://www.transifex.com/odoo/odoo-12-doc/translate/#fr/iot/155920666 but it still needs to be translated in French there

**Comment by rim-odoo** [comment]
Ok thanks @mart-e and apologies to the mighty @C3POdoo

**Comment by BamBalaam** [comment]
Hi @mart-e,

Since this was finally answered to, I had a second look at the docs. Here's two other small issues I found: 

https://github.com/odoo/documentation-user/blob/6e74e5dfea8ab24aa93b8fe42de8c43d6a3971fe/locale/fr/LC_MESSAGES/point_of_sale.po#L62-L68

Here the "translation" is a copy of the english text.

https://github.com/odoo/documentation-user/blob/6e74e5dfea8ab24aa93b8fe42de8c43d6a3971fe/locale/fr/LC_MESSAGES/website.po#L317-L320

Here the direct translation of a CSS tag will lead to invalid CSS.

**Comment by mart-e** [comment]
@BamBalaam for all these cases, please go to Transifex to correct these wrong translations, for the documentation 12.0, it is the project odoo-12-doc
See our translation documentation at: https://github.com/odoo/odoo/wiki/Translations
and let me know if you have issues
