### ISSUE TITLE
Fix default role

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/documentation-user#337]
In rST/sphinx, the single backtick is an alias for the "default role" which defaults (haha) to [implicit / title references](http://docutils.sourceforge.net/docs/user/rst/quickref.html#implicit-hyperlink-targets). This is not very useful, and we never implemented it in our theming which often generates warnings.

It's unclear what to define the default role to though:

* we could use "inline literal" (rST's double backtick) as that matches Markdown
* we could use sphinx's [`any`](http://www.sphinx-doc.org/en/1.5/markup/inline.html#role-any) as it exists pretty much for that reason, note that [we may still need some sort of fallback](https://stackoverflow.com/questions/37359407/suppress-warnings-for-unfound-references-with-default-role-any-in-sphinx) if writers use single backticks for stuff which is not a ref' to anything
* we could raise an error when it's used, though that assumes people who write doc at least build it let alone look at it (which is clearly not the case), or we add some sort of CI to the repo

/cc @mart-e

**Comment by AntoineVDV** [comment]
I vote for the "inline literal" option.
This doc is meant to be collaborative and people coming from Markdown will keep using this markup to highlight their technical terms. When it comes to build errors, I know for a fact that even those who build the doc don't read the build logs so...

**Comment by AntoineVDV** [comment]
We picked 'literal' in #760
