### ISSUE TITLE
Left Menu Blink

### ISSUE THREAD

**Issue by Tardo** [odoo/documentation-user#361]
When scroll to bottom, left menu "blink" (Firefox & Chromium)

For example here: https://www.odoo.com/documentation/user/11.0/purchase/overview/process/from_po_to_invoice.html

![doc_fail](https://user-images.githubusercontent.com/731270/60336383-7d72bf80-99a0-11e9-8ffc-e17d3c52ba20.gif)

**Comment by YairThuAung** [comment]
Well received.Please,let me know what things I do with thanks.

**Comment by AntoineVDV** [comment]
Fixed in #549
