### ISSUE TITLE
I can build the zh_CN lang ,but the generate zh-CN folder still english

### ISSUE THREAD

**Issue by samping** [odoo/documentation-user#377]
i run `make -e LANG=zh_CN i18nhtml`
it seem ok! but the generate folder in _build/html/zh_CN is still english
![image](https://user-images.githubusercontent.com/6119267/63163633-873ba980-c058-11e9-96b7-e5f782be6cec.png)
i nano index.html
![image](https://user-images.githubusercontent.com/6119267/63163656-9ae71000-c058-11e9-9767-cbc844199a0d.png)
it still in english! why!

**Comment by samping** [comment]
![image](https://user-images.githubusercontent.com/6119267/63163706-c833be00-c058-11e9-8d92-69ea3cf769f6.png)

**Comment by rim-odoo** [comment]
Hello

Translations of the Odoo user documentation are made by our community members on Transifex. (https://www.transifex.com/odoo/odoo-12-doc/language/zh_CN/)
We then regularly pull the translated terms from Transifex.

Nonetheless, it is possible that the documentation has not been translated yet to zh_CN
If you wish to contribute to our translation effort, please visit: https://github.com/odoo/odoo/wiki/Translations

cc @mart-e
