### ISSUE TITLE
Differentiate Odoo Community from Odoo Enterprise

### ISSUE THREAD

**Issue by flachica** [odoo/documentation-user#403]
I have found at the [following address](https://www.odoo.com/documentation/user/12.0/accounting/receivables/customer_invoices/overview.html#contracts) that refers to the contracts / subscriptions module. That module is only available in the Enterprise version. I propose that this circumstance be distinguished in some way. Maybe it's a good idea to review all the documentation to see if it happens on another occasion. Maybe I can do that if you give me some guidelines.

**Comment by rim-odoo** [comment]
Hello
We don't have that kind of distinction in our documentation, it covers the whole Odoo apps, from Community and Enterprise edition.
Best regards
