### ISSUE TITLE
Paypal Button Encoding

### ISSUE THREAD

**Issue by JPML94** [odoo/documentation-user#412]
https://www.odoo.com/documentation/user/12.0/fr/ecommerce/shopper_experience/paypal.html#payment-messages-format

I believe the setting within Paypal called Paypal Button language encoding is no longer available. Should we completely remove this from the instructions or is it in a new place? I haven't been able to locate it in the new paypal layout.

**Comment by rim-odoo** [comment]
Open a ticket, as this requires a technical investigation + maybe an update of the docs/screenshots
