### ISSUE TITLE
Request to activate Russian translation in transifex

### ISSUE THREAD

**Issue by yelizariev** [odoo/documentation-user#497]
It was already requested at transifex by someone else, but it's not accepted. Can someone add the language?

**Comment by rim-odoo** [comment]
@mart-e , if you have some time, can you help us with this one?

**Comment by mart-e** [comment]
Hi,

I see you have made a request on the project odoo-12-doc. Any reason not to work on odoo-13-doc directly? We are currently updating the documentation in that version so it should be of better quality (and it will be supported one year longer).

Also, we usually add languages for the documentation only once it is fully translated for the software. I see the version 13.0 is at 56% so it is probably worth focusing on improving it first before translating the documentation (which is again another good quantity of terms to translate).

Please note that when we add a new language on Transifex, it won't automatically be added on odoo.com/documentation/user. This will be done only once we reach a good percentage of completion.

**Comment by yelizariev** [comment]
Hi @mart-e 

I can start with odoo-13-doc. I initially requested for 12, because it's easy to translate, cause Ukranian language has better coverage there. Having translation in Ukranian, we can have a quite good automatic translation to Russian, cause the two are close to each other (see also https://github.com/odoo/odoo/pull/42271). Once I apply the automatic translation, it could be reviewed manually.

**Comment by mart-e** [comment]
Thanks for the reply, I have added Russian on odoo-13-doc.
We will publish it once it is ready.
Best,
