### ISSUE TITLE
Trial balance 

### ISSUE THREAD

**Issue by imanahmad** [odoo/documentation-user#5]
the report of trial balance show the balance of each account , i need a report calculating the total debit and total credit and tell me if they equal to say that trial balance is balanced

**Comment by mart-e** [comment]
Hello,

I don't think your question is asked at the right place. This repository is for the functional documentation published to [Odoo User Documentation](https://www.odoo.com/documentation/user/) currently in the process of redaction. This repository should be used to report errors in existing pages.

To ask help on Odoo you may try the [Community mailinglist](https://www.odoo.com/groups/community-59) (subscribe [here](https://www.odoo.com/groups)), the [forum](https://www.odoo.com/forum/help-1) or [contact](https://www.odoo.com/page/contactus) Odoo support.

Regarding your question on the trial balance, I am not sure what wish exactly but have a look at the balance sheet report. (but again, definitely not the best place to answer that question)
