### ISSUE TITLE
Is the "Sale and Purcuase Vouchers" module available in Enterprise?

### ISSUE THREAD

**Issue by HeneryH** [odoo/documentation-user#508]
Documentation - https://www.odoo.com/documentation/user/12.0/accounting/payables/supplier_bills/bills_or_receipts.html

I can't find the module noted...

[img]https://i.imgur.com/gcOhf4B.png[/img]

**Comment by RamblingFiddler** [comment]
Good day to you, @HeneryH .
This documentation is outdated.
You don't need to install that module and can go directly to _Accounting > Vendors > Receipts_ to record a new receipt.

The whole documentation is currently being updated :-)

Cheers, have a good day!

**Comment by RamblingFiddler** [comment]
I close the issue but feel free to re-open it if necessary.
