### ISSUE TITLE
[Accounting]Translation: How can I change the English images to Chinese images?

### ISSUE THREAD

**Issue by mengzeyang** [odoo/documentation-user#733]
How can I change the English images to Chinese images?
![image](https://user-images.githubusercontent.com/36189881/89185954-ad41bd00-d5cd-11ea-9345-c0497d9707ba.png)
![image](https://user-images.githubusercontent.com/36189881/89186021-c9ddf500-d5cd-11ea-8612-c172193f557b.png)
![image](https://user-images.githubusercontent.com/36189881/89186270-1e817000-d5ce-11ea-8484-07063cc1ad1f.png)

**Comment by jcs-odoo** [comment]
Hello @mengzeyang 

I am not completely sure what you want to do. Can you explain a bit more, please?
We keep our screenshots in English in our documentation, while the text translations are handled on Transifex.

Best regards,
Jonathan

**Comment by mengzeyang** [comment]
Hi,
When the visitor change the website language to Chinese, the text will be Chinese, but the images will keep English. Only the website manager can change the images?
Or need a PR to change the images? I'm working on the user docs translation...

Best regards,




Felix Yang/杨孟泽 [Certified Functional Consultant] - Shanghai Elico Limited
Skype & Phone: + 86 173 0213 8659 (Cell) // + 86 21 6211 8017/27 (Office)
More information: https://www.elico-corp.com


Odoo Gold Partner // Best Odoo Partner APAC 2014, 2016 and 2018! 

 
From: Jonathan
Date: 2020-08-04 17:25
To: odoo/documentation-user
CC: Felix Yang - Elico Corp; Mention
Subject: Re: [odoo/documentation-user] [Accounting]Translation: How can I change the English images to Chinese images? (#733)
Hello @mengzeyang
I am not completely sure what you want to do. Can you explain a bit more, please?
We keep our screenshots in English in our documentation, while the text translations are handled on Transifex.
Best regards,
Jonathan

**Comment by jcs-odoo** [comment]
Thanks for your reply @mengzeyang 

I am afraid this is the limitation for now.
The text can be translated on Transifex indeed (I assume that this is what you use for the translations), but the images can't be "translated" for now and remain in English for all languages. It is a technical limitation. Hopefully, this will be improved soon, but it is not doable for now.

Best regards,
Jonathan
