### ISSUE TITLE
Please enable pt_BR translation to version 12.0

### ISSUE THREAD

**Issue by mileo** [odoo/documentation-user#738]
Could someone do the immense favor of turning on translation for the Portuguese (Brazilian)?

Thanks in advance

**Comment by mileo** [comment]
![image](https://user-images.githubusercontent.com/1975978/90319840-7e531180-df12-11ea-97ce-a7d2af7a4bbf.png)

**Comment by mileo** [comment]
There are a lot of other languages pending too.

**Comment by mart-e** [comment]
Hi,

We are not going to add new languages to version 12 projects, we prefer focus on the version 13. There is already the pt_BR language in the project odoo-13-doc but it's not very active. It's best to focus the efforts on one version at a time.
https://www.transifex.com/odoo/odoo-13-doc/language/pt_BR/
If the pt_BR version of odoo-13-doc is well translated we can consider adding it for odoo-12-doc but we don't recommend it, the doc is a bit outdated.

More generally, we add language for the documentation only when the software is already well translated.
