### ISSUE TITLE
Documentation for Import needs to be updated

### ISSUE THREAD

**Issue by corradopagliarini-bikm** [odoo/documentation-user#756]
Impacted versions: 14

Official documentation https://www.odoo.com/documentation/user/14.0/general/base_import/import_faq.html is still saying that the Import menu is present while it should say that the function to use is in Favourites.

https://github.com/odoo/odoo/issues/59083

**Comment by corradopagliarini-bikm** [comment]
I opened the same issue on https://www.odoo.com/help.
The Support Team says that they "are currently working on updating the documentation for the new version: it may take some time for all the documents to be revised. However, this change is indeed quite impactful and controversial, so we will prioritise this update."

**Comment by jcs-odoo** [comment]
Hello,
Thanks for your request. We gave it the top priority indeed :) 
It's been updated with the PR #758 and should be online very soon, probably by tomorrow morning.

Have a good evening!
