### ISSUE TITLE
How to configure Odoo Accounting?

### ISSUE THREAD

**Issue by mmalorni** [odoo/documentation-user#8]
I think the documentation is  a bit terse. Assuming the user is new to Odoo, they might not know how to get to the screen displayed. We should mention to open the accounting module by clicking on the accounting icon on the main screen.
I would write "step-by-step wizard" instead of "step-by-step manual".
Although it should be clear, we should mention what access right is needed just in case.
We should mention that checking the box at the bottom will help keep track of the progress on the setup.
I don't know if there are other steps that should be done prior to this one but a link to the list of other config would be nice. Same for the next steps if there is something else that is not covered by the wizard.

**Comment by mart-e** [comment]
Hello,

Thank you for your suggestions. The advise to specify the menu in the app switcher is relevant for all modules so do you want to add it for every page ?
Can you specify which page exactly you are referring to ?

**Comment by fpodoo** [comment]
I did the change in the accounting configuration documenation that refers to this issue.
